# Generated by Django 5.2.16 on 2026-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'sku'],
                'indexes': [models.Index(fields=['sku'], name='product_sku_idx'), models.Index(fields=['name'], name='product_name_idx'), models.Index(fields=['category'], name='product_category_idx'), models.Index(fields=['is_active'], name='product_is_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='product_unit_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'code'],
                'indexes': [models.Index(fields=['code'], name='warehouse_code_idx'), models.Index(fields=['name'], name='warehouse_name_idx'), models.Index(fields=['is_active'], name='warehouse_is_active_idx')],
            },
        ),
    ]
