# Generated by Django 5.2.16 on 2026-07-10 12:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order_number'], name='order_number_idx'), models.Index(fields=['customer_email'], name='order_customer_email_idx'), models.Index(fields=['status'], name='order_status_idx'), models.Index(fields=['status', 'reserved_at'], name='order_expiration_idx'), models.Index(fields=['created_at'], name='order_created_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_amount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.warehouse')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order'], name='order_item_order_idx'), models.Index(fields=['product'], name='order_item_product_idx'), models.Index(fields=['warehouse'], name='order_item_warehouse_idx'), models.Index(fields=['order', 'product', 'warehouse'], name='order_item_order_prod_wh_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'product', 'warehouse'), name='unique_order_product_warehouse'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='order_item_unit_price_positive'), models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_item_subtotal_nonnegative')],
            },
        ),
    ]
