# Generated by Django 5.2.16 on 2026-07-10 14:52

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=100)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=apps.orders.models.default_idempotency_expires_at)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', 'operation', 'key'], name='idem_scope_idx'), models.Index(fields=['status'], name='idem_status_idx'), models.Index(fields=['expires_at'], name='idem_expires_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'operation', 'key'), name='unique_idempotency_actor_operation_key')],
            },
        ),
    ]
