# Generated by Django 5.2.16 on 2026-07-16 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_idempotencyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed', 'failed'])), name='idempotency_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'reserved', 'confirmed', 'cancelled', 'shipped'])), name='order_status_valid'),
        ),
    ]
