# Generated by Django 5.2.16 on 2026-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('adjustment', 'Adjustment'), ('stock_in', 'Stock in'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation release'), ('stock_out', 'Stock out'), ('manual_adjustment', 'Manual adjustment')], max_length=32),
        ),
    ]
