# Generated by Django 5.2.16 on 2026-07-16 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['adjustment', 'stock_in', 'reservation', 'reservation_release', 'stock_out', 'manual_adjustment'])), name='stock_movement_type_valid'),
        ),
    ]
