# Generated by Django 5.2.16 on 2026-07-10 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_updated', 'Product updated'), ('inventory_adjusted', 'Inventory adjusted'), ('order_reserved', 'Order reserved'), ('order_cancelled', 'Order cancelled'), ('order_confirmed', 'Order confirmed')], max_length=64)),
                ('target_model', models.CharField(max_length=100)),
                ('target_object_id', models.CharField(max_length=64)),
                ('target_repr', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['target_model', 'target_object_id'], name='audit_target_idx'), models.Index(fields=['correlation_id'], name='audit_correlation_idx'), models.Index(fields=['created_at'], name='audit_created_at_idx')],
            },
        ),
    ]
