# Generated by Django 5.2.16 on 2026-07-16 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['product_updated', 'inventory_adjusted', 'order_reserved', 'order_cancelled', 'order_confirmed'])), name='audit_action_valid'),
        ),
    ]
